### ndarray 정렬


In [1]:
import numpy as np
arr = np.random.randint(1,11,10)
arr

array([10,  6,  3,  9,  3,  2, 10,  8,  9,  3])

In [2]:
print(np.sort(arr))
print(arr)

[ 2  3  3  3  6  8  9  9 10 10]
[10  6  3  9  3  2 10  8  9  3]


#### 2차원 배열 정렬

In [10]:

arr = np.random.randint(10,size=(3,4)) # 0이상 10 미만
arr
print(arr)
print(np.sort(arr))


[[7 5 9 1]
 [6 9 1 9]
 [6 8 8 8]]
[[1 5 7 9]
 [1 6 9 9]
 [6 8 8 8]]


In [12]:
print(np.sort(arr,axis=0)) # 행방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr,axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[6 5 1 1]
 [6 8 8 8]
 [7 9 9 9]]
[[1 5 7 9]
 [1 6 9 9]
 [6 8 8 8]]


In [14]:
names = np.array(["리사",'로제','제니','지수'])
album_sales = np.array([900,870,1000,670])

print(np.sort(album_sales)[::1])
print(np.argsort(album_sales[::-1]))

sales_desc = np.argsort(album_sales)[::-1]
names[sales_desc]

[ 670  870  900 1000]
[0 2 3 1]


array(['제니', '리사', '로제', '지수'], dtype='<U2')

In [19]:
# arr = np.array([2025,2,28],[17,18,30])
# print(np.argsort(arr))
# print(np.argsort(arr,axis=1))
# print(np.argsort(arr,axis=0))

TypeError: Field elements must be 2- or 3-tuples, got '17'

In [5]:
#reshape()
import numpy as np
arr = np.array(range(11))
arr = arr.reshape(2,2,3)
print(arr.ndim,arr.shape)
print(arr)

TypeError: 'tuple' object is not callable