In [1]:
import numpy as np
arr = np.arange(50).reshape(5,10)
print(arr)
print(np.ravel(arr))


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [2]:
arr_2d = np.array([[1,2],[2,3]])
print(np.expand_dims(arr_2d,axis=0))
print(np.expand_dims(arr_2d,axis=0).shape)
print(np.expand_dims(arr_2d,axis=1))
print(np.expand_dims(arr_2d,axis=1).shape)

[[[1 2]
  [2 3]]]
(1, 2, 2)
[[[1 2]]

 [[2 3]]]
(2, 1, 2)


In [ ]:
#np.squeeze() : 차원의 값이 1일 때 제거
arr = np.array([[1,2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr,axis =0)
arr2 = np.squeeze(arr,axis =1)
print(arr2.shape)
