### ndarray 연산

### 기본 연산

In [1]:
import numpy as np

In [5]:
arr_a = np.arange(1,10).reshape(3,3)
arr_b = np.full_like(arr_a,3)
print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [7]:
print(arr_a+arr_b)
print(np.add(arr_a,arr_b))

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
# 뺄셈
print(arr_a-arr_b)

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [13]:
# 곱셈
print(arr_a*arr_b)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [17]:
# 나눗셈
print(arr_a / arr_b)

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [26]:
# 특수 연산 1 : 거듭 제곰
print(arr_a ** arr_b)
print(np.power(arr_a,arr_b))
print(np.square(arr_a)) # 제곱


[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[                   1                   16                19683]
 [          4294967296   298023223876953125 -5108087961858080768]
 [ 6812400838176574343                    0  8677311020002933897]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [31]:
# 특수 연산 2 : 몫
print(arr_a // arr_b)
print(np.floor_divide(arr_a,arr_b))


[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [32]:
# 특수 연산 3 : 나머지
print(arr_a % arr_b)
print(np.mod(arr_a,arr_b))

[[0 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# 특수 연산 4 : 제곱근
print(np.sqrt(arr_a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [53]:
sales_1 = [200,340,150,400]
sales_2 = [220,300,180,420]
print(np.add(sales_1,sales_2))
np.divide(np.add(arr_a,arr_b),2)

[420 640 330 820]


array([[ 1.,  3.,  6.],
       [10., 15., 21.],
       [28., 36., 45.]])

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [41]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


##### broadcasting 연산
- 두 배열의 shape이 다르면 broadingcasting 연산을 수행한다
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [54]:
result_arr = arr_a * np.array([[5,5,5],[5,5,5,],[5,5,5]])
result_arr = arr_a * np.array([5,5,5])
result_arr = arr_a * np.array([5])
resutl_arr = arr_a
resutl_arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([5,10,15]) # (3,)
arr1+arr2

array([[ 6, 12, 18],
       [ 9, 15, 21],
       [12, 18, 24]])

In [61]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[100],[200]])
print(arr1+arr2)


[[101 102 103]
 [204 205 206]]


In [67]:
arr1 = np.array([1,2,3])
arr2 = np.array([[4],[5],[6]])
arr1.shape,arr2.shape
arr1+arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [73]:
arr1 = np.array([[1,2,3],[1,2,3]]) # (2,3)
arr2 = np.array([1,2]) #(2,)
# arr1+arr2  에러 행의 갯수가 맞지 않음

##### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A,B의 곱셈은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두번째 행렬 B의 행의 수가 같아야 한다. 
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행 수,두번째 행렬 B의 열 수)이다.

In [87]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1*arr2)
print(arr1.shape,arr2.shape,(arr1*arr2).shape)
print(np.dot(arr1,arr2))

[[ 5 12]
 [21 32]]
(2, 2) (2, 2) (2, 2)
[[19 22]
 [43 50]]


In [101]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[7,8],[9,10],[11,12]])
print(np.dot(arr4,arr3))
arr3.shape,arr4.shape
# np.dot(arr4,arr3) -> (2,3) * (3,2) = (2,2)
# np.dot(arr3,arr4) -> (3,2) * (2,3) = (3,3)

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


((2, 3), (3, 2))

In [102]:
# Quiz! shape으로만 결과 판단하기
# (100,20000) (20000,100) : (100,100)
# (20000,100) (100,200000) : (20000,20000)
# (100,20000) (100,20000) : error

In [104]:
arr = np.array([[1,2,3],[4,5,6]])
# print(arr @ arr) # (2,3) (2,3)

# .T
print(arr.T)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


# 연산 함수 및 집계 함수

In [109]:
arr_negative = np.array([[-1,-2],[-100,-200]])
arr_float = np.array([[1.234,5.678],[7.89,10.123]])
arr = np.arange(1,7).reshape(2,3)
print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float,2))


[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.89 10.12]]


In [111]:
arr_float = np.array([[1.234,-5.678],[-7.89,10.123]])

#내림
print(np.floor(arr_float))

#버림(절삭)
print(np.trunc(arr_float))

[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [115]:
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.max(arr,axis=0))
print(np.min(arr,axis=1))

[[1 2 3]
 [4 5 6]]
6
1
[4 5 6]
[1 4]


In [117]:
#합계
print(arr.sum())
print(np.sum(arr))

print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
21
[5 7 9]
[ 6 15]


In [119]:
#평균
print(arr.mean())
print(np.mean(arr))

print(arr.mean(axis=0))
print(arr.mean(axis=1))
print(np.mean(arr))

3.5
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
