In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mp
from sklearn.datasets import load_iris

mp.rc('font',family='AppleGothic')
plt.rcParams['axes.unicode_minus']

True

In [2]:
iris_data = load_iris()
# iris_data.keys()
# iris_data["target"]
# iris_data.target_names
# iris_data.feature_names
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
print(iris_data.data)             # input 데이터 (특성 데이터)
print(iris_data.feature_names)    # 특성명

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
print(iris_data.target)             # 숫자로 인코딩 된 라벨 데이터 (정답)
print(iris_data.target_names)       # label명

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [5]:
# 데이터 전처리
# iris_input = pd.DataFrame(iris_data.data,columns=iris_data.feature_names)
# print(iris_input)


In [6]:
# 입력 - 라벨 데이터
iris_input = iris_data.data
iris_label = iris_data.target



In [28]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# 훈련 - 테스트 데이터
kn = KNeighborsClassifier()
standard_scaler = StandardScaler()

def training(test_size_in,random_state_in,return_type = 'score'):
    # 훈련 - 테스트 데이터 분리
    train_input, test_input, train_label, test_label = train_test_split(iris_input, iris_label, test_size=test_size_in, stratify=iris_label,random_state=random_state_in)
    #정규화
    train_scaled = standard_scaler.fit_transform(train_input)
    test_scaled = standard_scaler.transform(test_input)
    #학습
    kn.fit(train_scaled, train_label)
    #평가 데이터 반환
    if return_type == 'score':
        return kn.score(test_scaled,test_label)
    elif return_type == 'accuracy_score':
        return accuracy_score(test_label,kn.predict(test_scaled))


random_state_list =[]
for i in range(200):
    if  training(0.25,i,'accuracy_score')== 1:
        random_state_list.append(i)
    i += 1
    
    
print(random_state_list)

[2, 10, 50, 52, 55, 62, 72, 77, 88, 114, 122, 130, 141, 152, 155, 159, 162, 168, 179, 181, 184, 189]
